### PR TITLE
Update lib version

### PR DESCRIPTION
**Pull request by magnolia-k**

### CODE REVIEW

**Comment by ngocdaothanh** [comment]
Thanks 👍 I've merged the PR. I'll release a new version soon.

Info about Rhino 1.7.13:
https://github.com/mozilla/rhino/releases/tag/Rhino1_7_13_Release

**Comment by ngocdaothanh** [comment]
Status of support for ES6 etc. in Rhino engine:
http://mozilla.github.io/rhino/compat/engines.html

**Comment by magnolia-k** [comment]
Thanks, I use it in Scalate.

I'm glad you updated it.

https://github.com/scalate/scalate

**Comment by ngocdaothanh** [comment]
I'm trying to build for CoffeeScript 2.5.1 (https://coffeescript.org/v2/browser-compiler-legacy/coffeescript.js), but there's error:

```
scala> org.mozilla.javascript.tools.jsc.Main.main(
     |     "-opt 9 -nosource -o CoffeeScript -package tv.cnt.rhinocoffeescript coffeescript.js".split(" ")
     |   )
org.mozilla.classfile.ClassFileWriter$ClassFileFormatException: Program too complex: too big jump offset
  at org.mozilla.classfile.ClassFileWriter.fixLabelGotos(ClassFileWriter.java:1313)
  at org.mozilla.classfile.ClassFileWriter.stopMethod(ClassFileWriter.java:257)
  at org.mozilla.javascript.optimizer.BodyCodegen.generateBodyCode(BodyCodegen.java:63)
  at org.mozilla.javascript.optimizer.Codegen.generateCode(Codegen.java:312)
  at org.mozilla.javascript.optimizer.Codegen.compileToClassFile(Codegen.java:187)
  at org.mozilla.javascript.optimizer.ClassCompiler.compileToClassFiles(ClassCompiler.java:161)
  at org.mozilla.javascript.tools.jsc.Main.processSource(Main.java:249)
  at org.mozilla.javascript.tools.jsc.Main.main(Main.java:45)
  ... 33 elided
```

(Instruction to build: https://github.com/xitrum-framework/RhinoCoffeeScript/blob/master/dev/README.rst)

I've also tried building the un-minified version of CoffeeScript:
https://github.com/jashkenas/coffeescript/issues/5213

But I still got similar error.

Building for CoffeeScript 1.x is OK.

**Comment by ngocdaothanh** [comment]
Minified versions of CoffeeScript:
* 1.12.7: 198KB
* 2.5.1: 514KB (probably too big for Rhino)

**Comment by ngocdaothanh** [comment]
https://github.com/mozilla/rhino/issues/537

> Java only gives us 64K worth of space in a classfile. If the generated
bytecode for a particular script results in more than 64K of bytecode, then
the bytecode generator will fail.

**Comment by ngocdaothanh** [comment]
I've just released version 1.12.7. You should be able to download it from Maven in a few minutes.

**Pull request merged**
